# Generated by Django 5.2 on 2025-04-27 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcchub_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=16)),
                ('nome', models.CharField(max_length=255)),
                ('turma', models.CharField(max_length=16)),
                ('sala', models.CharField(max_length=32)),
                ('inicio', models.CharField(max_length=16)),
                ('fim', models.CharField(max_length=16)),
                ('dias', models.CharField(max_length=32)),
                ('professor', models.CharField(max_length=255)),
            ],
        ),
    ]
