# Generated by Django 5.2 on 2025-04-27 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcchub_app', '0002_disciplina'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disciplina',
            name='codigo',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='disciplina',
            name='dias',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='disciplina',
            name='fim',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='disciplina',
            name='inicio',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='disciplina',
            name='nome',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='disciplina',
            name='professor',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='disciplina',
            name='sala',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='disciplina',
            name='turma',
            field=models.CharField(max_length=10),
        ),
    ]
