# Generated by Django 5.2 on 2025-05-01 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dcchub_app', '0004_professor_alter_disciplina_professor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='senha',
        ),
    ]
