# Generated by Django 5.2 on 2025-05-03 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcchub_app', '0005_remove_user_senha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disciplina',
            name='codigo',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='disciplina',
            name='sala',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='disciplina',
            name='turma',
            field=models.CharField(max_length=15),
        ),
    ]
